export const reducerCases = {
    TOGGLE_LOGIN_MODEL: 'TOGGLE_LOGIN_MODEL',
    TOGGLE_SIGNUP_MODEL: 'TOGGLE_SIGNUP_MODEL',
    CLOSE_AUTH_MODEL: 'CLOSE_AUTH_MODEL',
    SET_USER: 'SET_USER',
    SWITCH_MODE: 'SWITCH_MODE',
    SET_GIG_DATA: 'SET_GIG_DATA',
    HAS_USER_ORDERED_GIG: 'HAS_USER_ORDERED_GIG',
    ADD_REVIEW: 'ADD_REVIEW',
    GET_ONLINE_USERS: 'GET_ONLINE_USERS',
    SOCKET: 'SOCKET',
    ONLINE_USERS: 'ONLINE_USERS'
}