export const reducerCases = {
    TOGGLE_LOGIN_MODEL: 'TOGGLE_LOGIN_MODEL',
    TOGGLE_SIGNUP_MODEL: 'TOGGLE_SIGNUP_MODEL',
    CLOSE_AUTH_MODEL: 'CLOSE_AUTH_MODEL',
    SET_USER: 'SET_USER',
    SWITCH_MODE: 'SWITCH_MODE'
}